proyectito/miPrimerApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings


app_name = "miPrimerApp"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('grupo/cinco/<str:grupo_id>', views.grupoCinco, name="grupoCinco"),
    path('grupo/seis/<str:grupo_id>', views.grupoSeis, name="grupoSeis"),
    path('grupo/siete/<str:grupo_id>', views.grupoSiete, name="grupoSiete")

]

proyectito/proyectito/urls.py
from django.contrib import admin
from miPrimerApp import views
from django.conf import settings
#se agrega
from  django.contrib.staticfiles.urls  import  staticfiles_urlpatterns
from  django.urls  import  path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("miPrimerApp.urls")),
]
urlpatterns  +=  staticfiles_urlpatterns()

proyectito/miPrimerApp/models.py
from django.db import models

# Create your models here.
class  Grupo(models.Model):
    id_grupo  =  models.AutoField(primary_key=True)

class  Estudiante(models.Model):
    numCta  =  models.IntegerField(default=0, max_length=9)
    nombres  =  models.CharField(max_length=200)
    apellidos  =  models.CharField(max_length=200)
    # Cada estudiante guarda el grupo en el que está inscrito
    grupo  =  models.ForeignKey(Grupo, on_delete=models.SET_NULL, null=True)

    def  __str__(self):
	    return  f'Nombre: {self.nombres} NumCta: {self.numCta}'

proyectito/miPrimerApp/views.py
from django.shortcuts import render
#agrgamos esta linea
from django.http import HttpResponse
#importamos modelos para usarlos
from .models import *

# Create your views here.
def index(request):
	consulta_Estudiante = Estudiante.objects.filter(grupo=5)
	grupo_id  =  Grupo.objects.get(id_grupo=5)
	grupo_idSeis  =  Grupo.objects.get(id_grupo=6)
	grupo_idSiete  =  Grupo.objects.get(id_grupo=7)

	return render(request, "index.html", {'consulta_Estudiante':consulta_Estudiante, 'grupo_id':grupo_id, 'grupo_idSeis':grupo_idSeis, 'grupo_idSiete':grupo_idSiete})

def  grupoCinco(request, grupo_id):
	consulta_Estudiante = Estudiante.objects.filter(grupo=5)
	return  render(request, "Grupo5.html", {'grupo_id':grupo_id, 'consulta_Estudiante':consulta_Estudiante})

def grupoSeis(request, grupo_id):
	consulta_Estudiante = Estudiante.objects.filter(grupo=6)
	return  render(request, "Grupo6.html", {'consulta_Estudiante':consulta_Estudiante})

def grupoSiete(request, grupo_id):
	consulta_Estudiante = Estudiante.objects.filter(grupo=7)
	return  render(request, "Grupo7.html", {'consulta_Estudiante':consulta_Estudiante})

proyectito/templates/Grupo5.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Página principal</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico'%}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
            <div class="container px-4">
                <a class="navbar-brand" href="/">Página principal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="#">Grupo 5</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header >
            <div class="container px-4 text-center">
                <h1 class="fw-bolder">Grupo 5 | DIU</h1>
                <p class="lead">Universidad Nacional Autónoma de México</p>
                
            </div>
        </header>
        <!-- About section-->

                <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-2 row-cols-xl-3 center-content ">
                    {% for i in consulta_Estudiante %}
                    <div class="col d-flex justify-content-center">
                        <br>
                        <div class="card" style="width: 18rem;">
                            <div class="card-body p-3">
                              <h5 class="card-title">{{i.nombres}}</h5>
                              <h6 class="card-subtitle mb-2 text-muted">{{i.apellidos}}</h6>
                              <p class="card-text">{{i.numCta}}</p>
                            </div>
                          </div>
                          <br>
                    </div>
                    {% endfor %}
                </div>
      

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

proyectito/templates/Grupo6.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Página principal</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico'%}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
            <div class="container px-4">
                <a class="navbar-brand" href="/">Página principal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="#services">Grupo 6</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header >
            <div class="container px-4 text-center">
                <h1 class="fw-bolder">Grupo 6 | DIU</h1>
                <p class="lead">Universidad Nacional Autónoma de México</p>
                
            </div>
        </header>
        <!-- About section-->
        <div  class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-2 row-cols-xl-3 center-content ">
            {% for i in consulta_Estudiante %}
                <div  class="col d-flex justify-content-center">
                    <br>
                    <div  class="card"  style="width: 18rem;">
                        <div  class="card-body p-3">
                            <h5  class="card-title">{{i.nombres}}</h5>
                            <h6  class="card-subtitle mb-2 text-muted">{{i.apellidos}}</h6>
                            <p  class="card-text">{{i.numCta}}</p>
                        </div>
                    </div>
                    <br>
                </div>
            {% endfor %}
        </div>
       
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

proyectito/templates/Grupo7.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Página principal</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico'%}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
            <div class="container px-4">
                <a class="navbar-brand" href="/">Página principal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="#">Grupo 7</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header >
            <div class="container px-4 text-center">
                <h1 class="fw-bolder">Grupo 7 | DIU</h1>
                <p class="lead">Universidad Nacional Autónoma de México</p>
                
            </div>
        </header>
        <!-- About section-->
        <div  class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-2 row-cols-xl-3 center-content ">
            {% for i in consulta_Estudiante %}
                <div  class="col d-flex justify-content-center">
                    <br>
                    <div  class="card"  style="width: 18rem;">
                        <div  class="card-body p-3">
                            <h5  class="card-title">{{i.nombres}}</h5>
                            <h6  class="card-subtitle mb-2 text-muted">{{i.apellidos}}</h6>
                            <p  class="card-text">{{i.numCta}}</p>
                        </div>
                    </div>
                    <br>
                </div>
            {% endfor %}
        </div>
       
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

proyectito/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Página principal</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico'%}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
            <div class="container px-4">
                <a class="navbar-brand" href="#page-top">Página principal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'miPrimerApp:grupoCinco' grupo_id=grupo_id %}">Grupo 5</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'miPrimerApp:grupoSeis' grupo_id=grupo_idSeis %}">Grupo 6</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'miPrimerApp:grupoSiete' grupo_id=grupo_idSiete %}">Grupo 7</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-primary bg-gradient text-white">
            <div class="container px-4 text-center">
                <h1 class="fw-bolder">Plantilla Bootstrap | DIU</h1>
                <p class="lead">Universidad Nacional Autónoma de México</p>
                <a class="btn btn-lg btn-light" href="#about">Facultad de ciencias</a>
            </div>
        </header>
        <!-- About section-->
        <section id="about">
            <div class="container px-4">
                <div class="row gx-4 justify-content-center">
                    <p>Esta es una página para visualizar cómo se vería una aplicación de Django con bootstrap, manejo de los modelos y urls contextualizadas a la página en la que se encuentre el usuario</p>
                </div>
            </div>
        </section>
       
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>